name: lxdgen

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^3.4.1
  code_builder: ^4.1.0
  collection: ^1.16.0
  dart_style: ^2.2.2
  meta: ^1.7.0
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
